name: deploy
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: false